### ISSUE TITLE
Models: Need to add Users table

### ISSUE THREAD

**Issue by sulochan** [rackerlabs/craton#46]
In order to have loose dependency with external auth service, we need to model a simple role based auth service inside the system. It therefore requires a User table to be added along with user roles that define what that particular user-api-key can do.

For example: we could have the following:

user-name: user1 ApiKety:11111-22222-33333 roles:[{"id":1, name:"read_write_host"}, {"id": 2, "name": "read_only_network"}]

so we can inject this on X-Roles into context and make required check to ensure that this user can only read network (top level key) but read and write any host data. This is a contrived example but this will go well with both simple auth and keystone based auth. Keystone already does Roles similar to this.

**Comment by jimbaker** [comment]
This looks good! Thanks for summarizing this nicely from our recent IRC discussion.

**Comment by sorrison** [comment]
Just wondering if we could utilize oslo_policy for this and maybe the neutron style for RBAC if also required? Would avoid the need for a user object which keystone already gives us.

**Comment by jimbaker** [comment]
Yes, we plan to use oslo.policy instead of Keystone when no undercloud capabilities are available.

Also, one further refinement: we want to distinguish permissions like read/write vs roles. In addition, we have also discussed having keys (namely top-level keys) or key prefix be roles. But this also needs to intersect with roles like being able to do something in a given label or cell for example.
