### ISSUE TITLE
Determine if we should use Storyboard for tracking the Craton project

### ISSUE THREAD

**Issue by b3rnard0** [rackerlabs/craton#91]
Look at pluses, negatives, and known issues for incorporating Storyboard for the Craton project.

**Comment by sigmavirus24** [comment]
Benefits: 

- Far nicer user experience and user interface
- Stories can be features or bug reports
- Stories can have sub-tasks
- Stories allow for easy tracking of backports when we have a stable branch
- Storyboard is integrated better with Gerrit and should be more reliable in that integration (it was built by OpenStack, for OpenStack)
- As we split out the craton CLI, storyboard will allow for cleaner/nicer cross-project integration/collaboration

Negatives:

- Still beta software (kind of?)
- We'd be early users and testers of the software
- Collecting metrics for Kanban reports will be challenging. I don't know if Storyboard has an API or where that's defined. We'd then have to write new tooling for collecting that information (versus Launchpad)
- The number of people actively working on storyboard (http://stackalytics.com/?module=storyboard) and storyboard's website (http://stackalytics.com/?module=storyboard-webclient) is pretty much less than a handful of people. Any bugs we find or features we need, will be hard to resolve unless we spend that effort/time.
- We would then have to use Launchpad (whose integration with gerrit (jeepyb) is flakey only due to Launchpad's API, but it can still track backports, and do cross-project work)


I'm sure there are more. If there are I may edit this post to avoid having too many posts of Positives & Negatives.

**Comment by jimbaker** [comment]
Closing this out. We can revisit Storyboard if it develops in maturity and capabilities, especially with respect to @sigmavirus24's comments. But for now we need to stick with Launchpad.
